import pandas as pd
import xml.dom.minidom as dm
X=pd.read_csv("emp.csv")
X=X.as_matrix()
doc=dm.Document()
e1=doc.createElement("Employees")
for i in range(4):
		es=doc.createElement('Employee')
		e11=doc.createElement('Eno')
		e12=doc.createTextNode(str(X[i,0]))
		e11.appendChild(e12)
		e2=doc.createElement('Ename') 
                e21=doc.createTextNode(str(X[i,1]))
 		e2.appendChild(e21)
		e3=doc.createElement('Edesig') 
                e31=doc.createTextNode(str(X[i,2]))
		e3.appendChild(e31)
		e4=doc.createElement('Esalary') 
                e41=doc.createTextNode(str(X[i,3]))
		e4.appendChild(e41)
		es.appendChild(e2)
		es.appendChild(e3)
		es.appendChild(e4)
		es.appendChild(e11)
		e1.appendChild(es)
fd=open("emp.xml","w")
e1.writexml(fd,indent="\t",addindent="\t",newl="\n")
fd.close()
