from Tkinter import *
mwin=Tk()
mwin.configure(background='Gray80')
vexp=""
def bhan(s):
	global vexp
	if s=='C':
		vexp=''
	elif s=='=':
		vexp=str(eval(vexp))
	else :
		vexp+=s
	t1.set(str(vexp))
mwin.title('CalcZilla')
mwin.geometry('275x380')
t1=StringVar()
e1=Entry(mwin,textvariable=t1,text='0')
f=('Times','20','bold')
e1.config(font=f,fg='#0F0',bg='#000')
b1=Button(mwin,text='1',command=lambda:bhan('1'),width=5,height=5)
b2=Button(mwin,text='2',command=lambda:bhan('2'),width=5,height=5)
b3=Button(mwin,text='3',command=lambda:bhan('3'),width=5,height=5)
b4=Button(mwin,text='4',command=lambda:bhan('4'),width=5,height=5)
b5=Button(mwin,text='5',command=lambda:bhan('5'),width=5,height=5)
b6=Button(mwin,text='6',command=lambda:bhan('6'),width=5,height=5)
b7=Button(mwin,text='7',command=lambda:bhan('7'),width=5,height=5)
b8=Button(mwin,text='8',command=lambda:bhan('8'),width=5,height=5)
b9=Button(mwin,text='9',command=lambda:bhan('9'),width=5,height=5)
b0=Button(mwin,text='0',command=lambda:bhan('0'),width=5,height=5)
bp=Button(mwin,text='+',command=lambda:bhan('+'),width=5,height=5)
bm=Button(mwin,text='-',command=lambda:bhan('-'),width=5,height=5)
be=Button(mwin,text='=',command=lambda:bhan('='),width=5,height=5)
bmul=Button(mwin,text='X',command=lambda:bhan('*'),width=5,height=5)
bdiv=Button(mwin,text='/',command=lambda:bhan('/'),width=5,height=5)
bdec=Button(mwin,text='.',command=lambda:bhan('.'),width=5,height=5)
bc=Button(mwin,text='C',command=lambda:bhan('C'),width=5,height=5)
e1.grid(row=0,column=0,columnspan=8)
b1.grid(row=4,column=0)
b2.grid(row=4,column=1)
b3.grid(row=4,column=2)
b4.grid(row=5,column=0)
b5.grid(row=5,column=1)
b6.grid(row=5,column=2)
b7.grid(row=6,column=0)
b8.grid(row=6,column=1)
b9.grid(row=6,column=2)
b0.grid(row=7,column=1)
bp.grid(row=4,column=4)
bm.grid(row=5,column=4)
be.grid(row=8,column=1,columnspan=2)
bmul.grid(row=6,column=4)
bdiv.grid(row=7,column=4)
bdec.grid(row=7,column=2)
bc.grid(row=7,column=0)
mwin.mainloop()

